name: Build TWA APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build TWA APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli@latest

      - name: Init Bubblewrap
        run: |
         yes | bubblewrap init --manifest=https://ngabsen.smkmaarif9kebumen.sch.id/manifest.json
   
      - name: Build APK
        run: bubblewrap build

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ngabsen-twa-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
